### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#501] opened 2024-10-02 12:32 UTC
The contents of the following template are not translated:

https://github.com/agdsn/sipa/blob/bd18e9e3215b49addac1398f7debf8a3b434ae55/sipa/templates/register/finish.html#L4-L8

**Comment by FestplattenSchnitzel** [comment] 2024-10-02 14:06
Duplicate of #459 .

**Closed** 2024-10-02 14:06 UTC
Labels: bug, easy task
