### ISSUE TITLE
Site broken on mobile devices.

### ISSUE THREAD

**Issue by janLo** [agdsn/sipa#111] opened 2015-09-24 13:37 UTC
Teh "landing page" on a mobile device shows nothing than "Contacts" without scrolling. Neither news nor a title what the site is about. Even when I select "News" from the menu - "Contacts" is the information I get. And it fills nearly the full screen in portrait mode and all in landscape mode.
![screenshot_2015-09-24-15-30-42](https://cloud.githubusercontent.com/assets/96146/10074729/fc3858ca-62d1-11e5-9d39-82081a1bbe44.png)
![screenshot_2015-09-24-15-30-50](https://cloud.githubusercontent.com/assets/96146/10074739/08221022-62d2-11e5-9fab-8b7e2648ef48.png)

Beside that the navication menu is not working in landscape mode. It does not show all entries and is NOT scrollable. So you cannot switch the language in that mode for example.
![screenshot_2015-09-24-15-30-54](https://cloud.githubusercontent.com/assets/96146/10074778/379d61c6-62d2-11e5-8f9e-a220c150c264.png)

**Comment by janLo** [comment] 2015-09-24 13:48
For the title you may replace the Icon in the top-left corner with a version with the name of the organization when the device-size is small enough to not show the header part from the full version (ow when the sandwich menu is shown).

**Comment by lukasjuhrich** [comment] 2015-09-24 18:57
This is a duplicate of #104. Replacing the icon is a good hint, thanks.

As far as I tested, the navigation menu is working indeed, although one has to scroll down, because it has a maximal height.

The problem (well, at least the cause for this behaviour) is that the pages width is fixed and thus the sidebar first squeezed and then moved to the top.

But let's move this discusion to #104 where it belongs.

**Closed** 2015-09-24 18:57 UTC
Labels: duplicate
