### ISSUE TITLE
Gerok member can't log in

### ISSUE THREAD

**Issue by toothstone** [agdsn/sipa#326] opened 2017-01-31 21:17 UTC
A specific member from Gerokstraße can't login via SIPA, but login at zaphod is working with the same credentials.

Related ticket: https://tickets.agdsn.de/index.pl?Action=AgentTicketZoom;TicketID=3030

**Comment by lukasjuhrich** [comment] 2017-02-01 16:20
I can reproduce it. It appears to be a Bug in the Gerok APi – the authentication works, but calling `cls.get(username)` results in `UserNotFound`, as the API query `find?login=<username>` does not return anything.

My guess is that for the user in question, `find` returns nothing because there are multiple users with that substring, as is observable by searching for `lukasjuhrich`, and then subsequently smaller parts of this string. At a certain length, the API stops giving the record for my User, most probably because other users start to contain this substring.

I will email The API author, but this isn't a bug that can be fixed in SIPA, so I will close this issue.

**Closed by lukasjuhrich** 2017-02-01 16:20 UTC
Labels: bug, model:gerok
