### ISSUE TITLE
missing disable email forwarding option in the usersuit 

### ISSUE THREAD

**Issue by wesx** [agdsn/sipa#346] opened 2017-10-18 09:42 UTC
At https://agdsn.de/sipa/usersuite/change-mail there is a possibility to change the email address, to which incoming mails are forwarded. Right now there is now possibility to disable the email forwarding and use just the agdsn mailbox instead.
If i leave the email address empty in the above mentioned dialog it complains about an invalid email address.

I would suggest to either make an extra option to enable/disable email forwarding or allowing an empty email address in the change dialog. The later option maybe should combined with an dialog asking if the user really wants to disable the forwarding.

**Comment by lukasjuhrich** [comment] 2017-10-18 12:31
Duplicate of #234, closing. Please redirect your efforts to said issue.

**Closed by lukasjuhrich** 2017-10-18 12:31 UTC
Labels: Hacktoberfest
